version: "3"

services:
        nginx:
                build: ./requirements/nginx/.
                image: nginx
                container_name: nginx
                restart: always
                volumes: 
                        - "html:/var/www/html"
                ports:
                        - "443:443"
                networks:
                        - "network"
                depends_on:
                        - wordpress
        mysql:
                build: requirements/mariadb/.
                container_name: mariadb
                image: mariadb

                env_file: .env

                restart: always

                volumes: 
                        - "mysql:/var/lib/mysql"
                networks: 
                        - "network"
                healthcheck:
                    test: "mariadb --password=$MYSQL_ROOT_PASSWORD --execute \"SHOW DATABASES;\""


        wordpress:

                build: requirements/wordpress/.
                container_name: wordpress
                image: wordpress

                env_file: .env

                restart: always

                volumes: 
                        - "html:/var/www/html"

                depends_on: 
                  mysql:
                    condition: service_healthy
                networks: 
                        - "network"

volumes:
    html:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/ybendavi/data/html

    mysql:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/ybendavi/data/mysql       

networks:
        network:
                driver: bridge
